ol.proj.proj4.register(proj4);
//ol.proj.get("EPSG:3067").setExtent([-666648.974640, 6468464.403193, 1857208.554973, 8168333.555537]);
var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            'type':'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_10kmrajavyhyke_1 = new ol.format.GeoJSON();
var features_10kmrajavyhyke_1 = format_10kmrajavyhyke_1.readFeatures(json_10kmrajavyhyke_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3067'});
var jsonSource_10kmrajavyhyke_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_10kmrajavyhyke_1.addFeatures(features_10kmrajavyhyke_1);
var lyr_10kmrajavyhyke_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_10kmrajavyhyke_1, 
                style: style_10kmrajavyhyke_1,
                popuplayertitle: '10km rajavyöhyke',
                interactive: true,
                title: '<img src="styles/legend/10kmrajavyhyke_1.png" /> <b>10km rajavyöhyke</b><P>Käyttö kielletty täysin'
            });
var format_40kmrajavyhyke_2 = new ol.format.GeoJSON();
var features_40kmrajavyhyke_2 = format_40kmrajavyhyke_2.readFeatures(json_40kmrajavyhyke_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3067'});
var jsonSource_40kmrajavyhyke_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_40kmrajavyhyke_2.addFeatures(features_40kmrajavyhyke_2);
var lyr_40kmrajavyhyke_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_40kmrajavyhyke_2, 
                style: style_40kmrajavyhyke_2,
                popuplayertitle: '40km rajavyöhyke',
                interactive: true,
                title: '<img src="styles/legend/40kmrajavyhyke_2.png" /> <b>40km rajavyöhyke</b><P>Tukiasemakäyttö kielletty antennin ollessa yli 5m korkeudessa'
            });

lyr_OpenStreetMap_0.setVisible(true);lyr_10kmrajavyhyke_1.setVisible(true);lyr_40kmrajavyhyke_2.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_10kmrajavyhyke_1,lyr_40kmrajavyhyke_2];
lyr_10kmrajavyhyke_1.set('fieldAliases', {'fid': 'fid', 'NAME_LEN': 'NAME_LEN', 'NAME_FR': 'NAME_FR', 'ISO_A3': 'ISO_A3', 'ISO_A2': 'ISO_A2', 'ABBREV_LEN': 'ABBREV_LEN', 'FIPS_10_': 'FIPS_10_', 'ECONOMY': 'ECONOMY', 'ADM0_A3_US': 'ADM0_A3_US', 'NAME_NL': 'NAME_NL', 'NAME_SORT': 'NAME_SORT', 'TINY': 'TINY', 'ADM0_DIF': 'ADM0_DIF', 'SUBREGION': 'SUBREGION', 'ADM0_A3_UN': 'ADM0_A3_UN', 'NAME_RU': 'NAME_RU', 'GDP_MD_EST': 'GDP_MD_EST', 'NAME_ES': 'NAME_ES', 'WIKIPEDIA': 'WIKIPEDIA', 'GDP_YEAR': 'GDP_YEAR', 'NAME_EL': 'NAME_EL', 'NAME_EN': 'NAME_EN', 'BRK_DIFF': 'BRK_DIFF', 'NAME_VI': 'NAME_VI', 'POP_RANK': 'POP_RANK', 'ISO_N3': 'ISO_N3', 'BRK_NAME': 'BRK_NAME', 'REGION_UN': 'REGION_UN', 'REGION_WB': 'REGION_WB', 'NOTE_BRK': 'NOTE_BRK', 'SUBUNIT': 'SUBUNIT', 'GU_A3': 'GU_A3', 'NAME_HU': 'NAME_HU', 'MAPCOLOR7': 'MAPCOLOR7', 'MAPCOLOR8': 'MAPCOLOR8', 'MAPCOLOR9': 'MAPCOLOR9', 'NAME_HI': 'NAME_HI', 'FORMAL_FR': 'FORMAL_FR', 'SU_A3': 'SU_A3', 'POP_EST': 'POP_EST', 'GEOUNIT': 'GEOUNIT', 'HOMEPART': 'HOMEPART', 'NAME_ALT': 'NAME_ALT', 'NAME_PL': 'NAME_PL', 'BRK_A3': 'BRK_A3', 'NAME_PT': 'NAME_PT', 'WOE_ID': 'WOE_ID', 'scalerank': 'scalerank', 'LASTCENSUS': 'LASTCENSUS', 'UN_A3': 'UN_A3', 'LABELRANK': 'LABELRANK', 'NAME_SV': 'NAME_SV', 'NAME_BN': 'NAME_BN', 'ABBREV': 'ABBREV', 'MIN_ZOOM': 'MIN_ZOOM', 'ADM0_A3_IS': 'ADM0_A3_IS', 'NAME_JA': 'NAME_JA', 'ADMIN': 'ADMIN', 'NAME_AR': 'NAME_AR', 'SOVEREIGNT': 'SOVEREIGNT', 'ISO_A3_EH': 'ISO_A3_EH', 'MAX_LABEL': 'MAX_LABEL', 'NAME_IT': 'NAME_IT', 'NAME': 'NAME', 'INCOME_GRP': 'INCOME_GRP', 'SOV_A3': 'SOV_A3', 'NOTE_ADM0': 'NOTE_ADM0', 'NAME_ID': 'NAME_ID', 'TYPE': 'TYPE', 'NAME_CIAWF': 'NAME_CIAWF', 'NAME_DE': 'NAME_DE', 'ADM0_A3': 'ADM0_A3', 'WIKIDATAID': 'WIKIDATAID', 'POSTAL': 'POSTAL', 'LONG_LEN': 'LONG_LEN', 'WOE_ID_EH': 'WOE_ID_EH', 'LEVEL': 'LEVEL', 'FORMAL_EN': 'FORMAL_EN', 'POP_YEAR': 'POP_YEAR', 'WOE_NOTE': 'WOE_NOTE', 'ADM0_A3_WB': 'ADM0_A3_WB', 'CONTINENT': 'CONTINENT', 'NAME_TR': 'NAME_TR', 'GEOU_DIF': 'GEOU_DIF', 'MAPCOLOR13': 'MAPCOLOR13', 'BRK_GROUP': 'BRK_GROUP', 'SU_DIF': 'SU_DIF', 'featurecla': 'featurecla', 'MIN_LABEL': 'MIN_LABEL', 'NAME_ZH': 'NAME_ZH', 'WB_A2': 'WB_A2', 'WB_A3': 'WB_A3', 'NAME_KO': 'NAME_KO', 'NE_ID': 'NE_ID', 'NAME_LONG': 'NAME_LONG', });
lyr_40kmrajavyhyke_2.set('fieldAliases', {'fid': 'fid', 'NAME_LEN': 'NAME_LEN', 'NAME_FR': 'NAME_FR', 'ISO_A3': 'ISO_A3', 'ISO_A2': 'ISO_A2', 'ABBREV_LEN': 'ABBREV_LEN', 'FIPS_10_': 'FIPS_10_', 'ECONOMY': 'ECONOMY', 'ADM0_A3_US': 'ADM0_A3_US', 'NAME_NL': 'NAME_NL', 'NAME_SORT': 'NAME_SORT', 'TINY': 'TINY', 'ADM0_DIF': 'ADM0_DIF', 'SUBREGION': 'SUBREGION', 'ADM0_A3_UN': 'ADM0_A3_UN', 'NAME_RU': 'NAME_RU', 'GDP_MD_EST': 'GDP_MD_EST', 'NAME_ES': 'NAME_ES', 'WIKIPEDIA': 'WIKIPEDIA', 'GDP_YEAR': 'GDP_YEAR', 'NAME_EL': 'NAME_EL', 'NAME_EN': 'NAME_EN', 'BRK_DIFF': 'BRK_DIFF', 'NAME_VI': 'NAME_VI', 'POP_RANK': 'POP_RANK', 'ISO_N3': 'ISO_N3', 'BRK_NAME': 'BRK_NAME', 'REGION_UN': 'REGION_UN', 'REGION_WB': 'REGION_WB', 'NOTE_BRK': 'NOTE_BRK', 'SUBUNIT': 'SUBUNIT', 'GU_A3': 'GU_A3', 'NAME_HU': 'NAME_HU', 'MAPCOLOR7': 'MAPCOLOR7', 'MAPCOLOR8': 'MAPCOLOR8', 'MAPCOLOR9': 'MAPCOLOR9', 'NAME_HI': 'NAME_HI', 'FORMAL_FR': 'FORMAL_FR', 'SU_A3': 'SU_A3', 'POP_EST': 'POP_EST', 'GEOUNIT': 'GEOUNIT', 'HOMEPART': 'HOMEPART', 'NAME_ALT': 'NAME_ALT', 'NAME_PL': 'NAME_PL', 'BRK_A3': 'BRK_A3', 'NAME_PT': 'NAME_PT', 'WOE_ID': 'WOE_ID', 'scalerank': 'scalerank', 'LASTCENSUS': 'LASTCENSUS', 'UN_A3': 'UN_A3', 'LABELRANK': 'LABELRANK', 'NAME_SV': 'NAME_SV', 'NAME_BN': 'NAME_BN', 'ABBREV': 'ABBREV', 'MIN_ZOOM': 'MIN_ZOOM', 'ADM0_A3_IS': 'ADM0_A3_IS', 'NAME_JA': 'NAME_JA', 'ADMIN': 'ADMIN', 'NAME_AR': 'NAME_AR', 'SOVEREIGNT': 'SOVEREIGNT', 'ISO_A3_EH': 'ISO_A3_EH', 'MAX_LABEL': 'MAX_LABEL', 'NAME_IT': 'NAME_IT', 'NAME': 'NAME', 'INCOME_GRP': 'INCOME_GRP', 'SOV_A3': 'SOV_A3', 'NOTE_ADM0': 'NOTE_ADM0', 'NAME_ID': 'NAME_ID', 'TYPE': 'TYPE', 'NAME_CIAWF': 'NAME_CIAWF', 'NAME_DE': 'NAME_DE', 'ADM0_A3': 'ADM0_A3', 'WIKIDATAID': 'WIKIDATAID', 'POSTAL': 'POSTAL', 'LONG_LEN': 'LONG_LEN', 'WOE_ID_EH': 'WOE_ID_EH', 'LEVEL': 'LEVEL', 'FORMAL_EN': 'FORMAL_EN', 'POP_YEAR': 'POP_YEAR', 'WOE_NOTE': 'WOE_NOTE', 'ADM0_A3_WB': 'ADM0_A3_WB', 'CONTINENT': 'CONTINENT', 'NAME_TR': 'NAME_TR', 'GEOU_DIF': 'GEOU_DIF', 'MAPCOLOR13': 'MAPCOLOR13', 'BRK_GROUP': 'BRK_GROUP', 'SU_DIF': 'SU_DIF', 'featurecla': 'featurecla', 'MIN_LABEL': 'MIN_LABEL', 'NAME_ZH': 'NAME_ZH', 'WB_A2': 'WB_A2', 'WB_A3': 'WB_A3', 'NAME_KO': 'NAME_KO', 'NE_ID': 'NE_ID', 'NAME_LONG': 'NAME_LONG', });
lyr_10kmrajavyhyke_1.set('fieldImages', {'fid': 'TextEdit', 'NAME_LEN': 'TextEdit', 'NAME_FR': 'TextEdit', 'ISO_A3': 'TextEdit', 'ISO_A2': 'TextEdit', 'ABBREV_LEN': 'TextEdit', 'FIPS_10_': 'TextEdit', 'ECONOMY': 'TextEdit', 'ADM0_A3_US': 'TextEdit', 'NAME_NL': 'TextEdit', 'NAME_SORT': 'TextEdit', 'TINY': 'TextEdit', 'ADM0_DIF': 'TextEdit', 'SUBREGION': 'TextEdit', 'ADM0_A3_UN': 'TextEdit', 'NAME_RU': 'TextEdit', 'GDP_MD_EST': 'TextEdit', 'NAME_ES': 'TextEdit', 'WIKIPEDIA': 'TextEdit', 'GDP_YEAR': 'TextEdit', 'NAME_EL': 'TextEdit', 'NAME_EN': 'TextEdit', 'BRK_DIFF': 'TextEdit', 'NAME_VI': 'TextEdit', 'POP_RANK': 'TextEdit', 'ISO_N3': 'TextEdit', 'BRK_NAME': 'TextEdit', 'REGION_UN': 'TextEdit', 'REGION_WB': 'TextEdit', 'NOTE_BRK': 'TextEdit', 'SUBUNIT': 'TextEdit', 'GU_A3': 'TextEdit', 'NAME_HU': 'TextEdit', 'MAPCOLOR7': 'TextEdit', 'MAPCOLOR8': 'TextEdit', 'MAPCOLOR9': 'TextEdit', 'NAME_HI': 'TextEdit', 'FORMAL_FR': 'TextEdit', 'SU_A3': 'TextEdit', 'POP_EST': 'TextEdit', 'GEOUNIT': 'TextEdit', 'HOMEPART': 'TextEdit', 'NAME_ALT': 'TextEdit', 'NAME_PL': 'TextEdit', 'BRK_A3': 'TextEdit', 'NAME_PT': 'TextEdit', 'WOE_ID': 'TextEdit', 'scalerank': 'TextEdit', 'LASTCENSUS': 'TextEdit', 'UN_A3': 'TextEdit', 'LABELRANK': 'TextEdit', 'NAME_SV': 'TextEdit', 'NAME_BN': 'TextEdit', 'ABBREV': 'TextEdit', 'MIN_ZOOM': 'TextEdit', 'ADM0_A3_IS': 'TextEdit', 'NAME_JA': 'TextEdit', 'ADMIN': 'TextEdit', 'NAME_AR': 'TextEdit', 'SOVEREIGNT': 'TextEdit', 'ISO_A3_EH': 'TextEdit', 'MAX_LABEL': 'TextEdit', 'NAME_IT': 'TextEdit', 'NAME': 'TextEdit', 'INCOME_GRP': 'TextEdit', 'SOV_A3': 'TextEdit', 'NOTE_ADM0': 'TextEdit', 'NAME_ID': 'TextEdit', 'TYPE': 'TextEdit', 'NAME_CIAWF': 'TextEdit', 'NAME_DE': 'TextEdit', 'ADM0_A3': 'TextEdit', 'WIKIDATAID': 'TextEdit', 'POSTAL': 'TextEdit', 'LONG_LEN': 'TextEdit', 'WOE_ID_EH': 'TextEdit', 'LEVEL': 'TextEdit', 'FORMAL_EN': 'TextEdit', 'POP_YEAR': 'TextEdit', 'WOE_NOTE': 'TextEdit', 'ADM0_A3_WB': 'TextEdit', 'CONTINENT': 'TextEdit', 'NAME_TR': 'TextEdit', 'GEOU_DIF': 'TextEdit', 'MAPCOLOR13': 'TextEdit', 'BRK_GROUP': 'TextEdit', 'SU_DIF': 'TextEdit', 'featurecla': 'TextEdit', 'MIN_LABEL': 'TextEdit', 'NAME_ZH': 'TextEdit', 'WB_A2': 'TextEdit', 'WB_A3': 'TextEdit', 'NAME_KO': 'TextEdit', 'NE_ID': 'TextEdit', 'NAME_LONG': 'TextEdit', });
lyr_40kmrajavyhyke_2.set('fieldImages', {'fid': 'TextEdit', 'NAME_LEN': 'TextEdit', 'NAME_FR': 'TextEdit', 'ISO_A3': 'TextEdit', 'ISO_A2': 'TextEdit', 'ABBREV_LEN': 'TextEdit', 'FIPS_10_': 'TextEdit', 'ECONOMY': 'TextEdit', 'ADM0_A3_US': 'TextEdit', 'NAME_NL': 'TextEdit', 'NAME_SORT': 'TextEdit', 'TINY': 'TextEdit', 'ADM0_DIF': 'TextEdit', 'SUBREGION': 'TextEdit', 'ADM0_A3_UN': 'TextEdit', 'NAME_RU': 'TextEdit', 'GDP_MD_EST': 'TextEdit', 'NAME_ES': 'TextEdit', 'WIKIPEDIA': 'TextEdit', 'GDP_YEAR': 'TextEdit', 'NAME_EL': 'TextEdit', 'NAME_EN': 'TextEdit', 'BRK_DIFF': 'TextEdit', 'NAME_VI': 'TextEdit', 'POP_RANK': 'TextEdit', 'ISO_N3': 'TextEdit', 'BRK_NAME': 'TextEdit', 'REGION_UN': 'TextEdit', 'REGION_WB': 'TextEdit', 'NOTE_BRK': 'TextEdit', 'SUBUNIT': 'TextEdit', 'GU_A3': 'TextEdit', 'NAME_HU': 'TextEdit', 'MAPCOLOR7': 'TextEdit', 'MAPCOLOR8': 'TextEdit', 'MAPCOLOR9': 'TextEdit', 'NAME_HI': 'TextEdit', 'FORMAL_FR': 'TextEdit', 'SU_A3': 'TextEdit', 'POP_EST': 'TextEdit', 'GEOUNIT': 'TextEdit', 'HOMEPART': 'TextEdit', 'NAME_ALT': 'TextEdit', 'NAME_PL': 'TextEdit', 'BRK_A3': 'TextEdit', 'NAME_PT': 'TextEdit', 'WOE_ID': 'TextEdit', 'scalerank': 'TextEdit', 'LASTCENSUS': 'TextEdit', 'UN_A3': 'TextEdit', 'LABELRANK': 'TextEdit', 'NAME_SV': 'TextEdit', 'NAME_BN': 'TextEdit', 'ABBREV': 'TextEdit', 'MIN_ZOOM': 'TextEdit', 'ADM0_A3_IS': 'TextEdit', 'NAME_JA': 'TextEdit', 'ADMIN': 'TextEdit', 'NAME_AR': 'TextEdit', 'SOVEREIGNT': 'TextEdit', 'ISO_A3_EH': 'TextEdit', 'MAX_LABEL': 'TextEdit', 'NAME_IT': 'TextEdit', 'NAME': 'TextEdit', 'INCOME_GRP': 'TextEdit', 'SOV_A3': 'TextEdit', 'NOTE_ADM0': 'TextEdit', 'NAME_ID': 'TextEdit', 'TYPE': 'TextEdit', 'NAME_CIAWF': 'TextEdit', 'NAME_DE': 'TextEdit', 'ADM0_A3': 'TextEdit', 'WIKIDATAID': 'TextEdit', 'POSTAL': 'TextEdit', 'LONG_LEN': 'TextEdit', 'WOE_ID_EH': 'TextEdit', 'LEVEL': 'TextEdit', 'FORMAL_EN': 'TextEdit', 'POP_YEAR': 'TextEdit', 'WOE_NOTE': 'TextEdit', 'ADM0_A3_WB': 'TextEdit', 'CONTINENT': 'TextEdit', 'NAME_TR': 'TextEdit', 'GEOU_DIF': 'TextEdit', 'MAPCOLOR13': 'TextEdit', 'BRK_GROUP': 'TextEdit', 'SU_DIF': 'TextEdit', 'featurecla': 'TextEdit', 'MIN_LABEL': 'TextEdit', 'NAME_ZH': 'TextEdit', 'WB_A2': 'TextEdit', 'WB_A3': 'TextEdit', 'NAME_KO': 'TextEdit', 'NE_ID': 'TextEdit', 'NAME_LONG': 'TextEdit', });
lyr_10kmrajavyhyke_1.set('fieldLabels', {'fid': 'hidden field', 'NAME_LEN': 'hidden field', 'NAME_FR': 'hidden field', 'ISO_A3': 'hidden field', 'ISO_A2': 'hidden field', 'ABBREV_LEN': 'hidden field', 'FIPS_10_': 'hidden field', 'ECONOMY': 'hidden field', 'ADM0_A3_US': 'hidden field', 'NAME_NL': 'hidden field', 'NAME_SORT': 'hidden field', 'TINY': 'hidden field', 'ADM0_DIF': 'hidden field', 'SUBREGION': 'hidden field', 'ADM0_A3_UN': 'hidden field', 'NAME_RU': 'hidden field', 'GDP_MD_EST': 'hidden field', 'NAME_ES': 'hidden field', 'WIKIPEDIA': 'hidden field', 'GDP_YEAR': 'hidden field', 'NAME_EL': 'hidden field', 'NAME_EN': 'hidden field', 'BRK_DIFF': 'hidden field', 'NAME_VI': 'hidden field', 'POP_RANK': 'hidden field', 'ISO_N3': 'hidden field', 'BRK_NAME': 'hidden field', 'REGION_UN': 'hidden field', 'REGION_WB': 'hidden field', 'NOTE_BRK': 'hidden field', 'SUBUNIT': 'hidden field', 'GU_A3': 'hidden field', 'NAME_HU': 'hidden field', 'MAPCOLOR7': 'hidden field', 'MAPCOLOR8': 'hidden field', 'MAPCOLOR9': 'hidden field', 'NAME_HI': 'hidden field', 'FORMAL_FR': 'hidden field', 'SU_A3': 'hidden field', 'POP_EST': 'hidden field', 'GEOUNIT': 'hidden field', 'HOMEPART': 'hidden field', 'NAME_ALT': 'hidden field', 'NAME_PL': 'hidden field', 'BRK_A3': 'hidden field', 'NAME_PT': 'hidden field', 'WOE_ID': 'hidden field', 'scalerank': 'hidden field', 'LASTCENSUS': 'hidden field', 'UN_A3': 'hidden field', 'LABELRANK': 'hidden field', 'NAME_SV': 'hidden field', 'NAME_BN': 'hidden field', 'ABBREV': 'hidden field', 'MIN_ZOOM': 'hidden field', 'ADM0_A3_IS': 'hidden field', 'NAME_JA': 'hidden field', 'ADMIN': 'hidden field', 'NAME_AR': 'hidden field', 'SOVEREIGNT': 'hidden field', 'ISO_A3_EH': 'hidden field', 'MAX_LABEL': 'hidden field', 'NAME_IT': 'hidden field', 'NAME': 'hidden field', 'INCOME_GRP': 'hidden field', 'SOV_A3': 'hidden field', 'NOTE_ADM0': 'hidden field', 'NAME_ID': 'hidden field', 'TYPE': 'hidden field', 'NAME_CIAWF': 'hidden field', 'NAME_DE': 'hidden field', 'ADM0_A3': 'hidden field', 'WIKIDATAID': 'hidden field', 'POSTAL': 'hidden field', 'LONG_LEN': 'hidden field', 'WOE_ID_EH': 'hidden field', 'LEVEL': 'hidden field', 'FORMAL_EN': 'hidden field', 'POP_YEAR': 'hidden field', 'WOE_NOTE': 'hidden field', 'ADM0_A3_WB': 'hidden field', 'CONTINENT': 'hidden field', 'NAME_TR': 'hidden field', 'GEOU_DIF': 'hidden field', 'MAPCOLOR13': 'hidden field', 'BRK_GROUP': 'hidden field', 'SU_DIF': 'hidden field', 'featurecla': 'hidden field', 'MIN_LABEL': 'hidden field', 'NAME_ZH': 'hidden field', 'WB_A2': 'hidden field', 'WB_A3': 'hidden field', 'NAME_KO': 'hidden field', 'NE_ID': 'hidden field', 'NAME_LONG': 'hidden field', });
lyr_40kmrajavyhyke_2.set('fieldLabels', {'fid': 'hidden field', 'NAME_LEN': 'hidden field', 'NAME_FR': 'hidden field', 'ISO_A3': 'hidden field', 'ISO_A2': 'hidden field', 'ABBREV_LEN': 'hidden field', 'FIPS_10_': 'hidden field', 'ECONOMY': 'hidden field', 'ADM0_A3_US': 'hidden field', 'NAME_NL': 'hidden field', 'NAME_SORT': 'hidden field', 'TINY': 'hidden field', 'ADM0_DIF': 'hidden field', 'SUBREGION': 'hidden field', 'ADM0_A3_UN': 'hidden field', 'NAME_RU': 'hidden field', 'GDP_MD_EST': 'hidden field', 'NAME_ES': 'hidden field', 'WIKIPEDIA': 'hidden field', 'GDP_YEAR': 'hidden field', 'NAME_EL': 'hidden field', 'NAME_EN': 'hidden field', 'BRK_DIFF': 'no label', 'NAME_VI': 'hidden field', 'POP_RANK': 'hidden field', 'ISO_N3': 'hidden field', 'BRK_NAME': 'hidden field', 'REGION_UN': 'hidden field', 'REGION_WB': 'hidden field', 'NOTE_BRK': 'hidden field', 'SUBUNIT': 'hidden field', 'GU_A3': 'hidden field', 'NAME_HU': 'hidden field', 'MAPCOLOR7': 'hidden field', 'MAPCOLOR8': 'hidden field', 'MAPCOLOR9': 'hidden field', 'NAME_HI': 'hidden field', 'FORMAL_FR': 'hidden field', 'SU_A3': 'hidden field', 'POP_EST': 'hidden field', 'GEOUNIT': 'hidden field', 'HOMEPART': 'hidden field', 'NAME_ALT': 'hidden field', 'NAME_PL': 'hidden field', 'BRK_A3': 'hidden field', 'NAME_PT': 'hidden field', 'WOE_ID': 'hidden field', 'scalerank': 'hidden field', 'LASTCENSUS': 'hidden field', 'UN_A3': 'hidden field', 'LABELRANK': 'hidden field', 'NAME_SV': 'hidden field', 'NAME_BN': 'hidden field', 'ABBREV': 'hidden field', 'MIN_ZOOM': 'hidden field', 'ADM0_A3_IS': 'hidden field', 'NAME_JA': 'hidden field', 'ADMIN': 'hidden field', 'NAME_AR': 'hidden field', 'SOVEREIGNT': 'hidden field', 'ISO_A3_EH': 'hidden field', 'MAX_LABEL': 'hidden field', 'NAME_IT': 'hidden field', 'NAME': 'hidden field', 'INCOME_GRP': 'hidden field', 'SOV_A3': 'hidden field', 'NOTE_ADM0': 'hidden field', 'NAME_ID': 'hidden field', 'TYPE': 'hidden field', 'NAME_CIAWF': 'hidden field', 'NAME_DE': 'hidden field', 'ADM0_A3': 'hidden field', 'WIKIDATAID': 'hidden field', 'POSTAL': 'hidden field', 'LONG_LEN': 'hidden field', 'WOE_ID_EH': 'hidden field', 'LEVEL': 'hidden field', 'FORMAL_EN': 'hidden field', 'POP_YEAR': 'hidden field', 'WOE_NOTE': 'hidden field', 'ADM0_A3_WB': 'hidden field', 'CONTINENT': 'hidden field', 'NAME_TR': 'hidden field', 'GEOU_DIF': 'hidden field', 'MAPCOLOR13': 'hidden field', 'BRK_GROUP': 'hidden field', 'SU_DIF': 'hidden field', 'featurecla': 'hidden field', 'MIN_LABEL': 'hidden field', 'NAME_ZH': 'hidden field', 'WB_A2': 'hidden field', 'WB_A3': 'hidden field', 'NAME_KO': 'hidden field', 'NE_ID': 'hidden field', 'NAME_LONG': 'hidden field', });
lyr_40kmrajavyhyke_2.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});